## Question 1

* Perceptron - learns by adjusting weights applied to features that get adusted based on the outcome of a training point. It is best for linearly separable data, but can be adjusted to handle non-linear to a degree. 'Learning rate' and 'epochs' are hyperparameters. Feature scaling is necessary, numerical data is best

* SVM - Perceptron's cooler brother. Tries to find an axis that provides the largest boundary between classes rather than minimize error. It can also be applied to non-linearly separated data. Hyperparameter C controls how much misclassification influences the decision boundary. Feature scaling is necessary, numerical data is best

* Decision Tree - Good model for interpretation and visualization. Classification occurs in a step-by-step manner where the feature resulting in the most correct classifications is selected at each step. Hyperparameter 'depth' controls the amount of levels a tree has. Too much depth leads to overfitting. Feature scaling is not necessary, nominal data or numerical

* Random Forest - a type of ensemble method that uses many decision trees with randomly selected training data (called a bootstrap sample), randomly selected features for classification, and large depth to obtain a decision by majority vote by the many trees. Each individual tree may suffer from overfitting but the final classification depends on the result from all trees and is beneficial for preventing overfitting. The number of trees 'k' is the most common hyperparameter, which is positively correlated to efficacy of the model but also positively correlated to computational cost. The size of the bootstrap sample and number of features for each tree may also be changed from defaults. Feature scaling not necessary, 

## Question 2

In [1]:
%matplotlib inline
import numpy as np
import pandas as pd

baseDir = 'C:/Users/abmad/Documents/School/JHU/Spring 2023/Applied Machine Learning/J Notebooks'

#downloaded from Kaggle, Tesla Autonomous Deaths Updated 2023
#https://www.kaggle.com/datasets/ibriiee/tesla-autonomous-deaths-data-updated-2023
teslaDF = pd.read_csv(baseDir + '/Datasets/Tesla Deaths - Deaths.csv')

print('Tesla Dataset')
print('Rows: ', len(teslaDF))
print('Features: ', len(teslaDF.columns))
teslaDF.head()

Tesla Dataset
Rows:  307
Features:  24


Case #    Year        Date  Country   State   \
0   294.0  2022.0   1/17/2023      USA       CA   
1   293.0  2022.0    1/7/2023   Canada        -   
2   292.0  2022.0    1/7/2023      USA       WA   
3   291.0  2022.0  12/22/2022      USA       GA   
4   290.0  2022.0  12/19/2022   Canada        -   

                         Description    Deaths   Tesla driver   \
0    Tesla crashes into back of semi        1.0             1    
1                      Tesla crashes        1.0             1    
2   Tesla hits pole, catches on fire        1.0             -    
3            Tesla crashes and burns        1.0             1    
4      Tesla crashes into storefront        1.0             -    

   Tesla occupant   Other vehicle   ...  Verified Tesla Autopilot Deaths   \
0               -               -   ...                                -    
1               -               -   ...                                -    
2               1               -   ...                                -    
3               -               -   ...                                -    
4               -               -   ...                                -    

   Verified Tesla Autopilot Deaths + All Deaths Reported to NHTSA SGO   \
0                                                 -                      
1                                                 -                      
2                                                 -                      
3                                                 -                      
4                                                 -                      

                                         Unnamed: 16  \
0   https://web.archive.org/web/20221222203930/ht...   
1   https://web.archive.org/web/20221222203930/ht...   
2   https://web.archive.org/web/20221222203930/ht...   
3   https://web.archive.org/web/20221222203930/ht...   
4   https://web.archive.org/web/20221223203725/ht...   

                                         Unnamed: 17  \
0   https://web.archive.org/web/20221222203930/ht...   
1   https://web.archive.org/web/20221222203930/ht...   
2   https://web.archive.org/web/20221222203930/ht...   
3   https://web.archive.org/web/20221222203930/ht...   
4   https://web.archive.org/web/20221223203725/ht...   

                                             Source   Note   \
0   https://web.archive.org/web/20230118162813/ht...    NaN   
1   https://web.archive.org/web/20230109041434/ht...    NaN   
2   https://web.archive.org/web/20230107232745/ht...    NaN   
3   https://web.archive.org/web/20221222203930/ht...    NaN   
4   https://web.archive.org/web/20221223203725/ht...    NaN   

         Deceased 1   Deceased 2   Deceased 3   Deceased 4   
0                NaN          NaN          NaN          NaN  
1   Taren Singh Lal           NaN          NaN          NaN  
2                NaN          NaN          NaN          NaN  
3                NaN          NaN          NaN          NaN  
4                NaN          NaN          NaN          NaN  

[5 rows x 24 columns]

In [2]:
from sklearn import datasets

#same image dataset used in Module 1 class notebook
nums = datasets.load_digits()
print(nums.images)
print(nums.DESCR)

[[[ 0.  0.  5. ...  1.  0.  0.]
  [ 0.  0. 13. ... 15.  5.  0.]
  [ 0.  3. 15. ... 11.  8.  0.]
  ...
  [ 0.  4. 11. ... 12.  7.  0.]
  [ 0.  2. 14. ... 12.  0.  0.]
  [ 0.  0.  6. ...  0.  0.  0.]]

 [[ 0.  0.  0. ...  5.  0.  0.]
  [ 0.  0.  0. ...  9.  0.  0.]
  [ 0.  0.  3. ...  6.  0.  0.]
  ...
  [ 0.  0.  1. ...  6.  0.  0.]
  [ 0.  0.  1. ...  6.  0.  0.]
  [ 0.  0.  0. ... 10.  0.  0.]]

 [[ 0.  0.  0. ... 12.  0.  0.]
  [ 0.  0.  3. ... 14.  0.  0.]
  [ 0.  0.  8. ... 16.  0.  0.]
  ...
  [ 0.  9. 16. ...  0.  0.  0.]
  [ 0.  3. 13. ... 11.  5.  0.]
  [ 0.  0.  0. ... 16.  9.  0.]]

 ...

 [[ 0.  0.  1. ...  1.  0.  0.]
  [ 0.  0. 13. ...  2.  1.  0.]
  [ 0.  0. 16. ... 16.  5.  0.]
  ...
  [ 0.  0. 16. ... 15.  0.  0.]
  [ 0.  0. 15. ... 16.  0.  0.]
  [ 0.  0.  2. ...  6.  0.  0.]]

 [[ 0.  0.  2. ...  0.  0.  0.]
  [ 0.  0. 14. ... 15.  1.  0.]
  [ 0.  4. 16. ... 16.  7.  0.]
  ...
  [ 0.  0.  0. ... 16.  2.  0.]
  [ 0.  0.  4. ... 16.  2.  0.]
  [ 0.  0.  5. ... 12.  0.  

* Numerical - integers and floating point values, they can be binned to make nominal data or left as-is depending on the model
    * year and number of deaths are floating point values in the Tesla data
    
    
* Nominal - a non-integer classification with a string name. Can be made into numerical data via one-hot encoding or assigning each possible classification an index correlating to a key table of classifications
    * Country is a nominal value in the Tesla dataset
    
    
* Date - can be given in a variety of formats, describes a day, month, and year. Can be nominalized into a date range then one-hot encoded to be numerical data or it can be given a numerical value by establishing a 'zero' time and increasing by one for each day past that point
    * Tesla data gives a date in the MM/DD/YYYY format
    
    
* Text - a string of some length. If it is used for classifying datapoints somehow then it can be transformed into numerical data as described for nominal data
    * Tesla data has a description feature and country feature which are valuable for different reasons. Description is best for human interpretation and exclusion from the model while the country is useful for both human interpretation and for the model depending on the dependent variable
    
    
* Image - these can come in many different formats and require specific libraries to parse them into usable formats (Ref. 1). In the sklearn dataset for handwritten digits they describe processing a 32X32 bitmap into an 8X8 bitmap where integer values give an intensity of coloring for a set of pixels.
    * The arrays of integers in the digits dataset represent black and white images of integers 0-9
    
    
    
* Dependent variable - This is the target of the dataset that the model is made to predict. It may be numerical or nominal but can be converted between the two.
    * In the digits dataset the dependent variable was the classification of the digit image as an integer 0-9

## Question 3

* Recall - The amount of positive classifications that were correct (Ref. 4)
    * Measured by dividing true positives (TP) by true positives plus false negatives (FN). 
    
    $$ Recall = \frac{TP}{TP +FN}\ $$
    
    

* AUC ROC - The ROC curve plots recall against false positive rate for different thresholds of classification. AUC stands for 'area under the curve', and refers to taking the integral of the ROC plot to get a representation of overall performance in classification (Ref. 2, 3, 4).
    * AUC is computed by taking the integral from 0 to 1 of the ROC plot
    
    

* F1 score - This uses precision (the percentage of correct positives out of all positives) and recall to let you know if both values are high, meaning the model is performing well (Ref. 2, 3)
    * Calculated using precision (P) and recall (R). 
    
    $$F1 = \frac{2}{\frac{1}{P}\+\frac{1}{R}\}\$$ 


* Mean squared error - Used for regression models. Finds average squared distance between actual values and predicted values. Squaring can make outliers have a large impact so the square root of MSE may also be used.

   $$
   MSE=\frac{1}{N}\sum\limits_{j=1}^{N}(y_{j}-\hat{y}_{j})^{2}
   $$
   
   
* Adjusted $R^{2}$ - a modified $R^{2}$ designed to prevent overfit models from misleading analysts. It accounts for the number of datapoints (n) and the number of independent variables (k) to prevent false increase in score (Ref. 2).

$$R^{2}_{a} = 1 - [(\frac{n-1}{n-k-1})(1-R^{2})]$$ 

## Question 4

In [3]:
import math

#simple average function
def average(list1):
    return sum(list1)/len(list1)

#computes the numerator of the Pearson correlation coefficient equation
def numerator(xAvg, xVals, yAvg, yVals):
    sum = 0
    for i in range(len(xVals)):
        sum = sum + ((xVals[i]-xAvg)*(yVals[i]-yAvg))
    return sum

#computes the denominator of the Pearson correlation coefficient equation
def denominator(xAvg, xVals, yAvg, yVals):
    sumX = 0
    sumY = 0
    for i in range(len(xVals)):
        sumX = sumX + pow((xVals[i]-xAvg),2)
        sumY = sumY + pow((yVals[i]-yAvg),2)
    
    return math.sqrt(sumX) * math.sqrt(sumY)

#computes a Pearson correlation coefficient for two sets of data
def pearson(xVals, yVals):
    xAvg = average(xVals)
    yAvg = average(yVals)
    
    num = numerator(xAvg, xVals, yAvg, yVals)
    denom = denominator(xAvg, xVals, yAvg, yVals)
    return num/denom

#original import of data downloaded from Kaggle
dataDF = pd.read_csv(baseDir + '/Datasets/GradAdmissions/Admission_Predict_Ver1.1.csv')

#removing the serial number column
cleanDataDF = dataDF.drop('Serial No.', axis = 1)

#converting to numpy array for easier manipulation
data = cleanDataDF.to_numpy()

#data is transposed such that data for each feature is separated by row
data = np.transpose(data)

pCorr = []

#Calculates the Pearson coefficient for every row combination in the 'data' matrix
for x in data:
    temp = []
    for y in data:
        temp.append(pearson(x, y))
    pCorr.append(temp)

myPCorr = pd.DataFrame(data = pCorr,index = cleanDataDF.columns, columns = cleanDataDF.columns)
myPCorr

GRE Score  TOEFL Score  University Rating       SOP  \
GRE Score           1.000000     0.827200           0.635376  0.613498   
TOEFL Score         0.827200     1.000000           0.649799  0.644410   
University Rating   0.635376     0.649799           1.000000  0.728024   
SOP                 0.613498     0.644410           0.728024  1.000000   
LOR                 0.524679     0.541563           0.608651  0.663707   
CGPA                0.825878     0.810574           0.705254  0.712154   
Research            0.563398     0.467012           0.427047  0.408116   
Chance of Admit     0.810351     0.792228           0.690132  0.684137   

                       LOR       CGPA  Research  Chance of Admit   
GRE Score          0.524679  0.825878  0.563398          0.810351  
TOEFL Score        0.541563  0.810574  0.467012          0.792228  
University Rating  0.608651  0.705254  0.427047          0.690132  
SOP                0.663707  0.712154  0.408116          0.684137  
LOR                1.000000  0.637469  0.372526          0.645365  
CGPA               0.637469  1.000000  0.501311          0.882413  
Research           0.372526  0.501311  1.000000          0.545871  
Chance of Admit    0.645365  0.882413  0.545871          1.000000

In [4]:
cleanDataDF.corr()

GRE Score  TOEFL Score  University Rating       SOP  \
GRE Score           1.000000     0.827200           0.635376  0.613498   
TOEFL Score         0.827200     1.000000           0.649799  0.644410   
University Rating   0.635376     0.649799           1.000000  0.728024   
SOP                 0.613498     0.644410           0.728024  1.000000   
LOR                 0.524679     0.541563           0.608651  0.663707   
CGPA                0.825878     0.810574           0.705254  0.712154   
Research            0.563398     0.467012           0.427047  0.408116   
Chance of Admit     0.810351     0.792228           0.690132  0.684137   

                       LOR       CGPA  Research  Chance of Admit   
GRE Score          0.524679  0.825878  0.563398          0.810351  
TOEFL Score        0.541563  0.810574  0.467012          0.792228  
University Rating  0.608651  0.705254  0.427047          0.690132  
SOP                0.663707  0.712154  0.408116          0.684137  
LOR                1.000000  0.637469  0.372526          0.645365  
CGPA               0.637469  1.000000  0.501311          0.882413  
Research           0.372526  0.501311  1.000000          0.545871  
Chance of Admit    0.645365  0.882413  0.545871          1.000000

The diagonal is all 1 because that is the point where each feature is being compared to itself. There is total positive correlation because it is the same data. 

The correlation between independent variables can reveal relationships between them that mean they may not be truly independent from one another. For example, GRE scores and TOEFL scores are positively associated with GPA. This could be because a high GPA reflects understanding of course materials and those materials may be helpful on the exams. If two independent variables are highly correlated then it would be appropriate to remove one of them as well.

The most important variable for prediciton should be the one with the highest correlation coefficient when used as an X value and chance of admission is the Y value. In this case, it appears that undergraduate GPA has the highest positive correlation with chance of admission, so I would assume that it has the most predictive power.

## References

1) For image formats in machine learning

https://stats.stackexchange.com/questions/440144/which-image-format-is-better-for-machine-learning-png-jpg-or-other

2) Used for Question 3

https://neptune.ai/blog/performance-metrics-in-machine-learning-complete-guide

3) Used for Question 3

https://www.tutorialspoint.com/machine_learning_with_python/machine_learning_algorithms_performance_metrics.htm

4) Used for Question 3

https://developers.google.com/machine-learning/crash-course/classification/roc-and-auc

5) DataFrame documentation used to figure out how to manipulate the data 

https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html